### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by nozim**
Improved usage example

### CODE REVIEW

**Comment by nozim** [comment]
@ryanfaerman @faxal thanks for this awesome lib.

**Comment by ryanfaerman** [comment]
This request has commits from a different request in it. I'm going to close this one for now, and if you still want to suggest the Readme changes, please just open a new pull request off a branch with only that commit.

Thanks!

**Comment by nozim** [comment]
sorry, will update the branch with just readme updates, thx.

**Comment by nozim** [comment]
https://github.com/ryanfaerman/fsm/pull/4

**Pull request closed without merging**
