### PR TITLE
Change the guard return type to error 

### PR DESCRIPTION
**Pull request by nozim**
By this you can provide ability to return exact
reason of guard rejection, nil if transition is valid

### CODE REVIEW

**Comment by ryanfaerman** [comment]
I'm generally not a huge fan of changing an existing public API and changing the return values here is definitely a breaking change. Any consumer of this package's API would need to be updated to work with `Guard` returning an `error` instead of a `bool`.

What problem are you trying to solve here?

**Comment by nozim** [comment]
I needed the way to specify why the guard did not pass in a way that I could test it. I could go and log the exact reason of guard failure but then I would have to mock logger and catch the arguments and etc.

**Comment by ryanfaerman** [comment]
I've found that when using a state machine, I haven't really needed to see why a particular guard failed because I try to define my states in a way that makes it fairly obvious. 

I'd love to see some example of a your use case to see if we can find a non-breaking way to solve your problem.

**Comment by nozim** [comment]
ok, Will try to give a very simple example:

let say we have flight booking with initial state "Confirmed" and I want to change it to "Cancelled", but I might have a couple guards, like is the booking cancellation time is expired or cancellation penalties can't be calculated due to other precondition. 

Maybe it's worth keeping this conditions outside of guard?

**Comment by mikeatlas** [comment]
@ryanfaerman you could create a v1 and v2 implementation with another branch using [gopkg.in](http://labix.org/gopkg.in) in order to not break downstream consumers.

**Comment by mikeatlas** [comment]
well anyways I like this so :+1: we pull in changes into forks of simpler dependencies for our projects, and this is a great idea from my perspective. Consider it "merged" in our project @nozim ;)

**Comment by ryanfaerman** [comment]
@mikeatlas I could create those branches, but then I'd have two separate branches to maintain. While it may be relatively easy at first and the package itself is fairly small right now, it's a practice I try to avoid. After reviewing the code again, using an error return time makes a bunch of sense and seems idiomatic.

@nozim If you fix the import path to it's correct form, I'll merge this pull request.

For anyone else using this package, this should be a relatively simple change and it shouldn't break anything out there already if folks are vendoring as they should be.

**Comment by nozim** [comment]
@ryanfaerman kindly review the updates.

**Pull request closed without merging**
